[package]
name = "countries-iso3166"
version = "1.0.2"
authors = ["448 ENGINEERING <superuser@448.africa>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Simple Conversion for Country Codes and Names using ISO 3166"
categories = ["internalization", "localization", "parsing"]
keywords = ["country-codes", "ISO-3166-1"]
homepage = "https://github.com/448-engineering/Countries-ISO3166"
repository = "https://github.com/448-engineering/Countries-ISO3166"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
