/// This is the country Code.
/// Working with country codes is much easier than working with country names
/// since some of them have special UTF-8 characters that can cause confusion.
#[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Clone, Copy, Hash)]
pub enum CountryIso31661 {
    AF,
    AX,
    AL,
    DZ,
    AS,
    AD,
    AO,
    AI,
    AQ,
    AG,
    AR,
    AM,
    AW,
    AU,
    AT,
    AZ,
    BS,
    BH,
    BD,
    BB,
    BY,
    BE,
    BZ,
    BJ,
    BM,
    BT,
    BO,
    BQ,
    BA,
    BW,
    BV,
    BR,
    IO,
    BN,
    BG,
    BF,
    BI,
    KH,
    CM,
    CA,
    CV,
    KY,
    CF,
    TD,
    CL,
    CN,
    CX,
    CC,
    CO,
    KM,
    CG,
    CD,
    CK,
    CR,
    CI,
    HR,
    CU,
    CW,
    CY,
    CZ,
    DK,
    DJ,
    DM,
    DO,
    EC,
    EG,
    SV,
    GQ,
    ER,
    EE,
    ET,
    FK,
    FO,
    FJ,
    FI,
    FR,
    GF,
    PF,
    TF,
    GA,
    GM,
    GE,
    DE,
    GH,
    GI,
    GR,
    GL,
    GD,
    GP,
    GU,
    GT,
    GG,
    GN,
    GW,
    GY,
    HT,
    HM,
    VA,
    HN,
    HK,
    HU,
    IS,
    IN,
    ID,
    IR,
    IQ,
    IE,
    IM,
    IL,
    IT,
    JM,
    JP,
    JE,
    JO,
    KZ,
    KE,
    KI,
    KP,
    KR,
    KW,
    KG,
    LA,
    LV,
    LB,
    LS,
    LR,
    LY,
    LI,
    LT,
    LU,
    MO,
    MK,
    MG,
    MW,
    MY,
    MV,
    ML,
    MT,
    MH,
    MQ,
    MR,
    MU,
    YT,
    MX,
    FM,
    MD,
    MC,
    MN,
    ME,
    MS,
    MA,
    MZ,
    MM,
    NA,
    NR,
    NP,
    NL,
    NC,
    NZ,
    NI,
    NE,
    NG,
    NU,
    NF,
    MP,
    NO,
    OM,
    PK,
    PW,
    PS,
    PA,
    PG,
    PY,
    PE,
    PH,
    PN,
    PL,
    PT,
    PR,
    QA,
    RE,
    RO,
    RU,
    RW,
    BL,
    SH,
    KN,
    LC,
    MF,
    PM,
    VC,
    WS,
    SM,
    ST,
    SA,
    SN,
    RS,
    SC,
    SL,
    SG,
    SX,
    SK,
    SI,
    SB,
    SO,
    ZA,
    GS,
    SS,
    ES,
    LK,
    SD,
    SR,
    SJ,
    SZ,
    SE,
    CH,
    SY,
    TW,
    TJ,
    TZ,
    TH,
    TL,
    TG,
    TK,
    TO,
    TT,
    TN,
    TR,
    TM,
    TC,
    TV,
    UG,
    UA,
    AE,
    GB,
    US,
    UM,
    UY,
    UZ,
    VU,
    VE,
    VN,
    VG,
    VI,
    WF,
    EH,
    YE,
    ZM,
    ZW,
    UnsupportedIso31661,
}

impl CountryIso31661 {
    pub fn country_code(&self) -> &'static str {
        match self {
            Self::AF => "AF",
            Self::AX => "AX",
            Self::AL => "AL",
            Self::DZ => "DZ",
            Self::AS => "AS",
            Self::AD => "AD",
            Self::AO => "AO",
            Self::AI => "AI",
            Self::AQ => "AQ",
            Self::AG => "AG",
            Self::AR => "AR",
            Self::AM => "AM",
            Self::AW => "AW",
            Self::AU => "AU",
            Self::AT => "AT",
            Self::AZ => "AZ",
            Self::BS => "BS",
            Self::BH => "BH",
            Self::BD => "BD",
            Self::BB => "BB",
            Self::BY => "BY",
            Self::BE => "BE",
            Self::BZ => "BZ",
            Self::BJ => "BJ",
            Self::BM => "BM",
            Self::BT => "BT",
            Self::BO => "BO",
            Self::BQ => "BQ",
            Self::BA => "BA",
            Self::BW => "BW",
            Self::BV => "BV",
            Self::BR => "BR",
            Self::IO => "IO",
            Self::BN => "BN",
            Self::BG => "BG",
            Self::BF => "BF",
            Self::BI => "BI",
            Self::KH => "KH",
            Self::CM => "CM",
            Self::CA => "CA",
            Self::CV => "CV",
            Self::KY => "KY",
            Self::CF => "CF",
            Self::TD => "TD",
            Self::CL => "CL",
            Self::CN => "CN",
            Self::CX => "CX",
            Self::CC => "CC",
            Self::CO => "CO",
            Self::KM => "KM",
            Self::CG => "CG",
            Self::CD => "CD",
            Self::CK => "CK",
            Self::CR => "CR",
            Self::CI => "CI",
            Self::HR => "HR",
            Self::CU => "CU",
            Self::CW => "CW",
            Self::CY => "CY",
            Self::CZ => "CZ",
            Self::DK => "DK",
            Self::DJ => "DJ",
            Self::DM => "DM",
            Self::DO => "DO",
            Self::EC => "EC",
            Self::EG => "EG",
            Self::SV => "SV",
            Self::GQ => "GQ",
            Self::ER => "ER",
            Self::EE => "EE",
            Self::ET => "ET",
            Self::FK => "FK",
            Self::FO => "FO",
            Self::FJ => "FJ",
            Self::FI => "FI",
            Self::FR => "FR",
            Self::GF => "GF",
            Self::PF => "PF",
            Self::TF => "TF",
            Self::GA => "GA",
            Self::GM => "GM",
            Self::GE => "GE",
            Self::DE => "DE",
            Self::GH => "GH",
            Self::GI => "GI",
            Self::GR => "GR",
            Self::GL => "GL",
            Self::GD => "GD",
            Self::GP => "GP",
            Self::GU => "GU",
            Self::GT => "GT",
            Self::GG => "GG",
            Self::GN => "GN",
            Self::GW => "GW",
            Self::GY => "GY",
            Self::HT => "HT",
            Self::HM => "HM",
            Self::VA => "VA",
            Self::HN => "HN",
            Self::HK => "HK",
            Self::HU => "HU",
            Self::IS => "IS",
            Self::IN => "IN",
            Self::ID => "ID",
            Self::IR => "IR",
            Self::IQ => "IQ",
            Self::IE => "IE",
            Self::IM => "IM",
            Self::IL => "IL",
            Self::IT => "IT",
            Self::JM => "JM",
            Self::JP => "JP",
            Self::JE => "JE",
            Self::JO => "JO",
            Self::KZ => "KZ",
            Self::KE => "KE",
            Self::KI => "KI",
            Self::KP => "KP",
            Self::KR => "KR",
            Self::KW => "KW",
            Self::KG => "KG",
            Self::LA => "LA",
            Self::LV => "LV",
            Self::LB => "LB",
            Self::LS => "LS",
            Self::LR => "LR",
            Self::LY => "LY",
            Self::LI => "LI",
            Self::LT => "LT",
            Self::LU => "LU",
            Self::MO => "MO",
            Self::MK => "MK",
            Self::MG => "MG",
            Self::MW => "MW",
            Self::MY => "MY",
            Self::MV => "MV",
            Self::ML => "ML",
            Self::MT => "MT",
            Self::MH => "MH",
            Self::MQ => "MQ",
            Self::MR => "MR",
            Self::MU => "MU",
            Self::YT => "YT",
            Self::MX => "MX",
            Self::FM => "FM",
            Self::MD => "MD",
            Self::MC => "MC",
            Self::MN => "MN",
            Self::ME => "ME",
            Self::MS => "MS",
            Self::MA => "MA",
            Self::MZ => "MZ",
            Self::MM => "MM",
            Self::NA => "NA",
            Self::NR => "NR",
            Self::NP => "NP",
            Self::NL => "NL",
            Self::NC => "NC",
            Self::NZ => "NZ",
            Self::NI => "NI",
            Self::NE => "NE",
            Self::NG => "NG",
            Self::NU => "NU",
            Self::NF => "NF",
            Self::MP => "MP",
            Self::NO => "NO",
            Self::OM => "OM",
            Self::PK => "PK",
            Self::PW => "PW",
            Self::PS => "PS",
            Self::PA => "PA",
            Self::PG => "PG",
            Self::PY => "PY",
            Self::PE => "PE",
            Self::PH => "PH",
            Self::PN => "PN",
            Self::PL => "PL",
            Self::PT => "PT",
            Self::PR => "PR",
            Self::QA => "QA",
            Self::RE => "RE",
            Self::RO => "RO",
            Self::RU => "RU",
            Self::RW => "RW",
            Self::BL => "BL",
            Self::SH => "SH",
            Self::KN => "KN",
            Self::LC => "LC",
            Self::MF => "MF",
            Self::PM => "PM",
            Self::VC => "VC",
            Self::WS => "WS",
            Self::SM => "SM",
            Self::ST => "ST",
            Self::SA => "SA",
            Self::SN => "SN",
            Self::RS => "RS",
            Self::SC => "SC",
            Self::SL => "SL",
            Self::SG => "SG",
            Self::SX => "SX",
            Self::SK => "SK",
            Self::SI => "SI",
            Self::SB => "SB",
            Self::SO => "SO",
            Self::ZA => "ZA",
            Self::GS => "GS",
            Self::SS => "SS",
            Self::ES => "ES",
            Self::LK => "LK",
            Self::SD => "SD",
            Self::SR => "SR",
            Self::SJ => "SJ",
            Self::SZ => "SZ",
            Self::SE => "SE",
            Self::CH => "CH",
            Self::SY => "SY",
            Self::TW => "TW",
            Self::TJ => "TJ",
            Self::TZ => "TZ",
            Self::TH => "TH",
            Self::TL => "TL",
            Self::TG => "TG",
            Self::TK => "TK",
            Self::TO => "TO",
            Self::TT => "TT",
            Self::TN => "TN",
            Self::TR => "TR",
            Self::TM => "TM",
            Self::TC => "TC",
            Self::TV => "TV",
            Self::UG => "UG",
            Self::UA => "UA",
            Self::AE => "AE",
            Self::GB => "GB",
            Self::US => "US",
            Self::UM => "UM",
            Self::UY => "UY",
            Self::UZ => "UZ",
            Self::VU => "VU",
            Self::VE => "VE",
            Self::VN => "VN",
            Self::VG => "VG",
            Self::VI => "VI",
            Self::WF => "WF",
            Self::EH => "EH",
            Self::YE => "YE",
            Self::ZM => "ZM",
            Self::ZW => "ZW",
            Self::UnsupportedIso31661 => "Invalid",
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::AF => "Afghanistan",
            Self::AX => "Åland Islands",
            Self::AL => "Albania",
            Self::DZ => "Algeria",
            Self::AS => "American Samoa",
            Self::AD => "Andorra",
            Self::AO => "Angola",
            Self::AI => "Anguilla",
            Self::AQ => "Antarctica",
            Self::AG => "Antigua and Barbuda",
            Self::AR => "Argentina",
            Self::AM => "Armenia",
            Self::AW => "Aruba",
            Self::AU => "Australia",
            Self::AT => "Austria",
            Self::AZ => "Azerbaijan",
            Self::BS => "Bahamas",
            Self::BH => "Bahrain",
            Self::BD => "Bangladesh",
            Self::BB => "Barbados",
            Self::BY => "Belarus",
            Self::BE => "Belgium",
            Self::BZ => "Belize",
            Self::BJ => "Benin",
            Self::BM => "Bermuda",
            Self::BT => "Bhutan",
            Self::BO => "Bolivia, Plurinational State of",
            Self::BQ => "Bonaire, Sint Eustatius and Saba",
            Self::BA => "Bosnia and Herzegovina",
            Self::BW => "Botswana",
            Self::BV => "Bouvet Island",
            Self::BR => "Brazil",
            Self::IO => "British Indian Ocean Territory",
            Self::BN => "Brunei Darussalam",
            Self::BG => "Bulgaria",
            Self::BF => "Burkina Faso",
            Self::BI => "Burundi",
            Self::KH => "Cambodia",
            Self::CM => "Cameroon",
            Self::CA => "Canada",
            Self::CV => "Cape Verde",
            Self::KY => "Cayman Islands",
            Self::CF => "Central African Republic",
            Self::TD => "Chad",
            Self::CL => "Chile",
            Self::CN => "China",
            Self::CX => "Christmas Island",
            Self::CC => "Cocos (Keeling) Islands",
            Self::CO => "Colombia",
            Self::KM => "Comoros",
            Self::CG => "Congo",
            Self::CD => "Congo, the Democratic Republic of the",
            Self::CK => "Cook Islands",
            Self::CR => "Costa Rica",
            Self::CI => "Côte d'Ivoire",
            Self::HR => "Croatia",
            Self::CU => "Cuba",
            Self::CW => "Curaçao",
            Self::CY => "Cyprus",
            Self::CZ => "Czech Republic",
            Self::DK => "Denmark",
            Self::DJ => "Djibouti",
            Self::DM => "Dominica",
            Self::DO => "Dominican Republic",
            Self::EC => "Ecuador",
            Self::EG => "Egypt",
            Self::SV => "El Salvador",
            Self::GQ => "Equatorial Guinea",
            Self::ER => "Eritrea",
            Self::EE => "Estonia",
            Self::ET => "Ethiopia",
            Self::FK => "Falkland Islands (Malvinas)",
            Self::FO => "Faroe Islands",
            Self::FJ => "Fiji",
            Self::FI => "Finland",
            Self::FR => "France",
            Self::GF => "French Guiana",
            Self::PF => "French Polynesia",
            Self::TF => "French Southern Territories",
            Self::GA => "Gabon",
            Self::GM => "Gambia",
            Self::GE => "Georgia",
            Self::DE => "Germany",
            Self::GH => "Ghana",
            Self::GI => "Gibraltar",
            Self::GR => "Greece",
            Self::GL => "Greenland",
            Self::GD => "Grenada",
            Self::GP => "Guadeloupe",
            Self::GU => "Guam",
            Self::GT => "Guatemala",
            Self::GG => "Guernsey",
            Self::GN => "Guinea",
            Self::GW => "Guinea-Bissau",
            Self::GY => "Guyana",
            Self::HT => "Haiti",
            Self::HM => "Heard Island and McDonald Islands",
            Self::VA => "Holy See (Vatican City State)",
            Self::HN => "Honduras",
            Self::HK => "Hong Kong",
            Self::HU => "Hungary",
            Self::IS => "Iceland",
            Self::IN => "India",
            Self::ID => "Indonesia",
            Self::IR => "Iran, Islamic Republic of",
            Self::IQ => "Iraq",
            Self::IE => "Ireland",
            Self::IM => "Isle of Man",
            Self::IL => "Israel",
            Self::IT => "Italy",
            Self::JM => "Jamaica",
            Self::JP => "Japan",
            Self::JE => "Jersey",
            Self::JO => "Jordan",
            Self::KZ => "Kazakhstan",
            Self::KE => "Kenya",
            Self::KI => "Kiribati",
            Self::KP => "Korea, Democratic People's Republic of",
            Self::KR => "Korea, Republic of",
            Self::KW => "Kuwait",
            Self::KG => "Kyrgyzstan",
            Self::LA => "Lao People's Democratic Republic",
            Self::LV => "Latvia",
            Self::LB => "Lebanon",
            Self::LS => "Lesotho",
            Self::LR => "Liberia",
            Self::LY => "Libya",
            Self::LI => "Liechtenstein",
            Self::LT => "Lithuania",
            Self::LU => "Luxembourg",
            Self::MO => "Macao",
            Self::MK => "Macedonia, the Former Yugoslav Republic of",
            Self::MG => "Madagascar",
            Self::MW => "Malawi",
            Self::MY => "Malaysia",
            Self::MV => "Maldives",
            Self::ML => "Mali",
            Self::MT => "Malta",
            Self::MH => "Marshall Islands",
            Self::MQ => "Martinique",
            Self::MR => "Mauritania",
            Self::MU => "Mauritius",
            Self::YT => "Mayotte",
            Self::MX => "Mexico",
            Self::FM => "Micronesia, Federated States of",
            Self::MD => "Moldova, Republic of",
            Self::MC => "Monaco",
            Self::MN => "Mongolia",
            Self::ME => "Montenegro",
            Self::MS => "Montserrat",
            Self::MA => "Morocco",
            Self::MZ => "Mozambique",
            Self::MM => "Myanmar",
            Self::NA => "Namibia",
            Self::NR => "Nauru",
            Self::NP => "Nepal",
            Self::NL => "Netherlands",
            Self::NC => "New Caledonia",
            Self::NZ => "New Zealand",
            Self::NI => "Nicaragua",
            Self::NE => "Niger",
            Self::NG => "Nigeria",
            Self::NU => "Niue",
            Self::NF => "Norfolk Island",
            Self::MP => "Northern Mariana Islands",
            Self::NO => "Norway",
            Self::OM => "Oman",
            Self::PK => "Pakistan",
            Self::PW => "Palau",
            Self::PS => "Palestine, State of",
            Self::PA => "Panama",
            Self::PG => "Papua New Guinea",
            Self::PY => "Paraguay",
            Self::PE => "Peru",
            Self::PH => "Philippines",
            Self::PN => "Pitcairn",
            Self::PL => "Poland",
            Self::PT => "Portugal",
            Self::PR => "Puerto Rico",
            Self::QA => "Qatar",
            Self::RE => "Réunion",
            Self::RO => "Romania",
            Self::RU => "Russian Federation",
            Self::RW => "Rwanda",
            Self::BL => "Saint Barthélemy",
            Self::SH => "Saint Helena, Ascension and Tristan da Cunha",
            Self::KN => "Saint Kitts and Nevis",
            Self::LC => "Saint Lucia",
            Self::MF => "Saint Martin (French part)",
            Self::PM => "Saint Pierre and Miquelon",
            Self::VC => "Saint Vincent and the Grenadines",
            Self::WS => "Samoa",
            Self::SM => "San Marino",
            Self::ST => "Sao Tome and Principe",
            Self::SA => "Saudi Arabia",
            Self::SN => "Senegal",
            Self::RS => "Serbia",
            Self::SC => "Seychelles",
            Self::SL => "Sierra Leone",
            Self::SG => "Singapore",
            Self::SX => "Sint Maarten (Dutch part)",
            Self::SK => "Slovakia",
            Self::SI => "Slovenia",
            Self::SB => "Solomon Islands",
            Self::SO => "Somalia",
            Self::ZA => "South Africa",
            Self::GS => "South Georgia and the South Sandwich Islands",
            Self::SS => "South Sudan",
            Self::ES => "Spain",
            Self::LK => "Sri Lanka",
            Self::SD => "Sudan",
            Self::SR => "Suriname",
            Self::SJ => "Svalbard and Jan Mayen",
            Self::SZ => "Swaziland",
            Self::SE => "Sweden",
            Self::CH => "Switzerland",
            Self::SY => "Syrian Arab Republic",
            Self::TW => "Taiwan, Province of China",
            Self::TJ => "Tajikistan",
            Self::TZ => "Tanzania, United Republic of",
            Self::TH => "Thailand",
            Self::TL => "Timor-Leste",
            Self::TG => "Togo",
            Self::TK => "Tokelau",
            Self::TO => "Tonga",
            Self::TT => "Trinidad and Tobago",
            Self::TN => "Tunisia",
            Self::TR => "Turkey",
            Self::TM => "Turkmenistan",
            Self::TC => "Turks and Caicos Islands",
            Self::TV => "Tuvalu",
            Self::UG => "Uganda",
            Self::UA => "Ukraine",
            Self::AE => "United Arab Emirates",
            Self::GB => "United Kingdom",
            Self::US => "United States",
            Self::UM => "United States Minor Outlying Islands",
            Self::UY => "Uruguay",
            Self::UZ => "Uzbekistan",
            Self::VU => "Vanuatu",
            Self::VE => "Venezuela, Bolivarian Republic of",
            Self::VN => "Viet Nam",
            Self::VG => "Virgin Islands, British",
            Self::VI => "Virgin Islands, U.S.",
            Self::WF => "Wallis and Futuna",
            Self::EH => "Western Sahara",
            Self::YE => "Yemen",
            Self::ZM => "Zambia",
            Self::ZW => "Zimbabwe",
            Self::UnsupportedIso31661 => "InvalidCountry",
        }
    }
}

impl From<CountryIso31661> for &str {
    fn from(value: CountryIso31661) -> Self {
        value.as_str()
    }
}

impl From<&str> for CountryIso31661 {
    fn from(value: &str) -> Self {
        match value {
            m if m == Self::AF.as_str() || m == Self::AF.country_code() => Self::AF,
            m if m == Self::AX.as_str() || m == Self::AX.country_code() => Self::AX,
            m if m == Self::AL.as_str() || m == Self::AL.country_code() => Self::AL,
            m if m == Self::DZ.as_str() || m == Self::DZ.country_code() => Self::DZ,
            m if m == Self::AS.as_str() || m == Self::AS.country_code() => Self::AS,
            m if m == Self::AD.as_str() || m == Self::AD.country_code() => Self::AD,
            m if m == Self::AO.as_str() || m == Self::AO.country_code() => Self::AO,
            m if m == Self::AI.as_str() || m == Self::AI.country_code() => Self::AI,
            m if m == Self::AQ.as_str() || m == Self::AQ.country_code() => Self::AQ,
            m if m == Self::AG.as_str() || m == Self::AG.country_code() => Self::AG,
            m if m == Self::AR.as_str() || m == Self::AR.country_code() => Self::AR,
            m if m == Self::AM.as_str() || m == Self::AM.country_code() => Self::AM,
            m if m == Self::AW.as_str() || m == Self::AW.country_code() => Self::AW,
            m if m == Self::AU.as_str() || m == Self::AU.country_code() => Self::AU,
            m if m == Self::AT.as_str() || m == Self::AT.country_code() => Self::AT,
            m if m == Self::AZ.as_str() || m == Self::AZ.country_code() => Self::AZ,
            m if m == Self::BS.as_str() || m == Self::BS.country_code() => Self::BS,
            m if m == Self::BH.as_str() || m == Self::BH.country_code() => Self::BH,
            m if m == Self::BD.as_str() || m == Self::BD.country_code() => Self::BD,
            m if m == Self::BB.as_str() || m == Self::BB.country_code() => Self::BB,
            m if m == Self::BY.as_str() || m == Self::BY.country_code() => Self::BY,
            m if m == Self::BE.as_str() || m == Self::BE.country_code() => Self::BE,
            m if m == Self::BZ.as_str() || m == Self::BZ.country_code() => Self::BZ,
            m if m == Self::BJ.as_str() || m == Self::BJ.country_code() => Self::BJ,
            m if m == Self::BM.as_str() || m == Self::BM.country_code() => Self::BM,
            m if m == Self::BT.as_str() || m == Self::BT.country_code() => Self::BT,
            m if m == Self::BO.as_str() || m == Self::BO.country_code() => Self::BO,
            m if m == Self::BQ.as_str() || m == Self::BQ.country_code() => Self::BQ,
            m if m == Self::BA.as_str() || m == Self::BA.country_code() => Self::BA,
            m if m == Self::BW.as_str() || m == Self::BW.country_code() => Self::BW,
            m if m == Self::BV.as_str() || m == Self::BV.country_code() => Self::BV,
            m if m == Self::BR.as_str() || m == Self::BR.country_code() => Self::BR,
            m if m == Self::IO.as_str() || m == Self::IO.country_code() => Self::IO,
            m if m == Self::BN.as_str() || m == Self::BN.country_code() => Self::BN,
            m if m == Self::BG.as_str() || m == Self::BG.country_code() => Self::BG,
            m if m == Self::BF.as_str() || m == Self::BF.country_code() => Self::BF,
            m if m == Self::BI.as_str() || m == Self::BI.country_code() => Self::BI,
            m if m == Self::KH.as_str() || m == Self::KH.country_code() => Self::KH,
            m if m == Self::CM.as_str() || m == Self::CM.country_code() => Self::CM,
            m if m == Self::CA.as_str() || m == Self::CA.country_code() => Self::CA,
            m if m == Self::CV.as_str() || m == Self::CV.country_code() => Self::CV,
            m if m == Self::KY.as_str() || m == Self::KY.country_code() => Self::KY,
            m if m == Self::CF.as_str() || m == Self::CF.country_code() => Self::CF,
            m if m == Self::TD.as_str() || m == Self::TD.country_code() => Self::TD,
            m if m == Self::CL.as_str() || m == Self::CL.country_code() => Self::CL,
            m if m == Self::CN.as_str() || m == Self::CN.country_code() => Self::CN,
            m if m == Self::CX.as_str() || m == Self::CX.country_code() => Self::CX,
            m if m == Self::CC.as_str() || m == Self::CC.country_code() => Self::CC,
            m if m == Self::CO.as_str() || m == Self::CO.country_code() => Self::CO,
            m if m == Self::KM.as_str() || m == Self::KM.country_code() => Self::KM,
            m if m == Self::CG.as_str() || m == Self::CG.country_code() => Self::CG,
            m if m == Self::CD.as_str() || m == Self::CD.country_code() => Self::CD,
            m if m == Self::CK.as_str() || m == Self::CK.country_code() => Self::CK,
            m if m == Self::CR.as_str() || m == Self::CR.country_code() => Self::CR,
            m if m == Self::CI.as_str() || m == Self::CI.country_code() => Self::CI,
            m if m == Self::HR.as_str() || m == Self::HR.country_code() => Self::HR,
            m if m == Self::CU.as_str() || m == Self::CU.country_code() => Self::CU,
            m if m == Self::CW.as_str() || m == Self::CW.country_code() => Self::CW,
            m if m == Self::CY.as_str() || m == Self::CY.country_code() => Self::CY,
            m if m == Self::CZ.as_str() || m == Self::CZ.country_code() => Self::CZ,
            m if m == Self::DK.as_str() || m == Self::DK.country_code() => Self::DK,
            m if m == Self::DJ.as_str() || m == Self::DJ.country_code() => Self::DJ,
            m if m == Self::DM.as_str() || m == Self::DM.country_code() => Self::DM,
            m if m == Self::DO.as_str() || m == Self::DO.country_code() => Self::DO,
            m if m == Self::EC.as_str() || m == Self::EC.country_code() => Self::EC,
            m if m == Self::EG.as_str() || m == Self::EG.country_code() => Self::EG,
            m if m == Self::SV.as_str() || m == Self::SV.country_code() => Self::SV,
            m if m == Self::GQ.as_str() || m == Self::GQ.country_code() => Self::GQ,
            m if m == Self::ER.as_str() || m == Self::ER.country_code() => Self::ER,
            m if m == Self::EE.as_str() || m == Self::EE.country_code() => Self::EE,
            m if m == Self::ET.as_str() || m == Self::ET.country_code() => Self::ET,
            m if m == Self::FK.as_str() || m == Self::FK.country_code() => Self::FK,
            m if m == Self::FO.as_str() || m == Self::FO.country_code() => Self::FO,
            m if m == Self::FJ.as_str() || m == Self::FJ.country_code() => Self::FJ,
            m if m == Self::FI.as_str() || m == Self::FI.country_code() => Self::FI,
            m if m == Self::FR.as_str() || m == Self::FR.country_code() => Self::FR,
            m if m == Self::GF.as_str() || m == Self::GF.country_code() => Self::GF,
            m if m == Self::PF.as_str() || m == Self::PF.country_code() => Self::PF,
            m if m == Self::TF.as_str() || m == Self::TF.country_code() => Self::TF,
            m if m == Self::GA.as_str() || m == Self::GA.country_code() => Self::GA,
            m if m == Self::GM.as_str() || m == Self::GM.country_code() => Self::GM,
            m if m == Self::GE.as_str() || m == Self::GE.country_code() => Self::GE,
            m if m == Self::DE.as_str() || m == Self::DE.country_code() => Self::DE,
            m if m == Self::GH.as_str() || m == Self::GH.country_code() => Self::GH,
            m if m == Self::GI.as_str() || m == Self::GI.country_code() => Self::GI,
            m if m == Self::GR.as_str() || m == Self::GR.country_code() => Self::GR,
            m if m == Self::GL.as_str() || m == Self::GL.country_code() => Self::GL,
            m if m == Self::GD.as_str() || m == Self::GD.country_code() => Self::GD,
            m if m == Self::GP.as_str() || m == Self::GP.country_code() => Self::GP,
            m if m == Self::GU.as_str() || m == Self::GU.country_code() => Self::GU,
            m if m == Self::GT.as_str() || m == Self::GT.country_code() => Self::GT,
            m if m == Self::GG.as_str() || m == Self::GG.country_code() => Self::GG,
            m if m == Self::GN.as_str() || m == Self::GN.country_code() => Self::GN,
            m if m == Self::GW.as_str() || m == Self::GW.country_code() => Self::GW,
            m if m == Self::GY.as_str() || m == Self::GY.country_code() => Self::GY,
            m if m == Self::HT.as_str() || m == Self::HT.country_code() => Self::HT,
            m if m == Self::HM.as_str() || m == Self::HM.country_code() => Self::HM,
            m if m == Self::VA.as_str() || m == Self::VA.country_code() => Self::VA,
            m if m == Self::HN.as_str() || m == Self::HN.country_code() => Self::HN,
            m if m == Self::HK.as_str() || m == Self::HK.country_code() => Self::HK,
            m if m == Self::HU.as_str() || m == Self::HU.country_code() => Self::HU,
            m if m == Self::IS.as_str() || m == Self::IS.country_code() => Self::IS,
            m if m == Self::IN.as_str() || m == Self::IN.country_code() => Self::IN,
            m if m == Self::ID.as_str() || m == Self::ID.country_code() => Self::ID,
            m if m == Self::IR.as_str() || m == Self::IR.country_code() => Self::IR,
            m if m == Self::IQ.as_str() || m == Self::IQ.country_code() => Self::IQ,
            m if m == Self::IE.as_str() || m == Self::IE.country_code() => Self::IE,
            m if m == Self::IM.as_str() || m == Self::IM.country_code() => Self::IM,
            m if m == Self::IL.as_str() || m == Self::IL.country_code() => Self::IL,
            m if m == Self::IT.as_str() || m == Self::IT.country_code() => Self::IT,
            m if m == Self::JM.as_str() || m == Self::JM.country_code() => Self::JM,
            m if m == Self::JP.as_str() || m == Self::JP.country_code() => Self::JP,
            m if m == Self::JE.as_str() || m == Self::JE.country_code() => Self::JE,
            m if m == Self::JO.as_str() || m == Self::JO.country_code() => Self::JO,
            m if m == Self::KZ.as_str() || m == Self::KZ.country_code() => Self::KZ,
            m if m == Self::KE.as_str() || m == Self::KE.country_code() => Self::KE,
            m if m == Self::KI.as_str() || m == Self::KI.country_code() => Self::KI,
            m if m == Self::KP.as_str() || m == Self::KP.country_code() => Self::KP,
            m if m == Self::KR.as_str() || m == Self::KR.country_code() => Self::KR,
            m if m == Self::KW.as_str() || m == Self::KW.country_code() => Self::KW,
            m if m == Self::KG.as_str() || m == Self::KG.country_code() => Self::KG,
            m if m == Self::LA.as_str() || m == Self::LA.country_code() => Self::LA,
            m if m == Self::LV.as_str() || m == Self::LV.country_code() => Self::LV,
            m if m == Self::LB.as_str() || m == Self::LB.country_code() => Self::LB,
            m if m == Self::LS.as_str() || m == Self::LS.country_code() => Self::LS,
            m if m == Self::LR.as_str() || m == Self::LR.country_code() => Self::LR,
            m if m == Self::LY.as_str() || m == Self::LY.country_code() => Self::LY,
            m if m == Self::LI.as_str() || m == Self::LI.country_code() => Self::LI,
            m if m == Self::LT.as_str() || m == Self::LT.country_code() => Self::LT,
            m if m == Self::LU.as_str() || m == Self::LU.country_code() => Self::LU,
            m if m == Self::MO.as_str() || m == Self::MO.country_code() => Self::MO,
            m if m == Self::MK.as_str() || m == Self::MK.country_code() => Self::MK,
            m if m == Self::MG.as_str() || m == Self::MG.country_code() => Self::MG,
            m if m == Self::MW.as_str() || m == Self::MW.country_code() => Self::MW,
            m if m == Self::MY.as_str() || m == Self::MY.country_code() => Self::MY,
            m if m == Self::MV.as_str() || m == Self::MV.country_code() => Self::MV,
            m if m == Self::ML.as_str() || m == Self::ML.country_code() => Self::ML,
            m if m == Self::MT.as_str() || m == Self::MT.country_code() => Self::MT,
            m if m == Self::MH.as_str() || m == Self::MH.country_code() => Self::MH,
            m if m == Self::MQ.as_str() || m == Self::MQ.country_code() => Self::MQ,
            m if m == Self::MR.as_str() || m == Self::MR.country_code() => Self::MR,
            m if m == Self::MU.as_str() || m == Self::MU.country_code() => Self::MU,
            m if m == Self::YT.as_str() || m == Self::YT.country_code() => Self::YT,
            m if m == Self::MX.as_str() || m == Self::MX.country_code() => Self::MX,
            m if m == Self::FM.as_str() || m == Self::FM.country_code() => Self::FM,
            m if m == Self::MD.as_str() || m == Self::MD.country_code() => Self::MD,
            m if m == Self::MC.as_str() || m == Self::MC.country_code() => Self::MC,
            m if m == Self::MN.as_str() || m == Self::MN.country_code() => Self::MN,
            m if m == Self::ME.as_str() || m == Self::ME.country_code() => Self::ME,
            m if m == Self::MS.as_str() || m == Self::MS.country_code() => Self::MS,
            m if m == Self::MA.as_str() || m == Self::MA.country_code() => Self::MA,
            m if m == Self::MZ.as_str() || m == Self::MZ.country_code() => Self::MZ,
            m if m == Self::MM.as_str() || m == Self::MM.country_code() => Self::MM,
            m if m == Self::NA.as_str() || m == Self::NA.country_code() => Self::NA,
            m if m == Self::NR.as_str() || m == Self::NR.country_code() => Self::NR,
            m if m == Self::NP.as_str() || m == Self::NP.country_code() => Self::NP,
            m if m == Self::NL.as_str() || m == Self::NL.country_code() => Self::NL,
            m if m == Self::NC.as_str() || m == Self::NC.country_code() => Self::NC,
            m if m == Self::NZ.as_str() || m == Self::NZ.country_code() => Self::NZ,
            m if m == Self::NI.as_str() || m == Self::NI.country_code() => Self::NI,
            m if m == Self::NE.as_str() || m == Self::NE.country_code() => Self::NE,
            m if m == Self::NG.as_str() || m == Self::NG.country_code() => Self::NG,
            m if m == Self::NU.as_str() || m == Self::NU.country_code() => Self::NU,
            m if m == Self::NF.as_str() || m == Self::NF.country_code() => Self::NF,
            m if m == Self::MP.as_str() || m == Self::MP.country_code() => Self::MP,
            m if m == Self::NO.as_str() || m == Self::NO.country_code() => Self::NO,
            m if m == Self::OM.as_str() || m == Self::OM.country_code() => Self::OM,
            m if m == Self::PK.as_str() || m == Self::PK.country_code() => Self::PK,
            m if m == Self::PW.as_str() || m == Self::PW.country_code() => Self::PW,
            m if m == Self::PS.as_str() || m == Self::PS.country_code() => Self::PS,
            m if m == Self::PA.as_str() || m == Self::PA.country_code() => Self::PA,
            m if m == Self::PG.as_str() || m == Self::PG.country_code() => Self::PG,
            m if m == Self::PY.as_str() || m == Self::PY.country_code() => Self::PY,
            m if m == Self::PE.as_str() || m == Self::PE.country_code() => Self::PE,
            m if m == Self::PH.as_str() || m == Self::PH.country_code() => Self::PH,
            m if m == Self::PN.as_str() || m == Self::PN.country_code() => Self::PN,
            m if m == Self::PL.as_str() || m == Self::PL.country_code() => Self::PL,
            m if m == Self::PT.as_str() || m == Self::PT.country_code() => Self::PT,
            m if m == Self::PR.as_str() || m == Self::PR.country_code() => Self::PR,
            m if m == Self::QA.as_str() || m == Self::QA.country_code() => Self::QA,
            m if m == Self::RE.as_str() || m == Self::RE.country_code() => Self::RE,
            m if m == Self::RO.as_str() || m == Self::RO.country_code() => Self::RO,
            m if m == Self::RU.as_str() || m == Self::RU.country_code() => Self::RU,
            m if m == Self::RW.as_str() || m == Self::RW.country_code() => Self::RW,
            m if m == Self::BL.as_str() || m == Self::BL.country_code() => Self::BL,
            m if m == Self::SH.as_str() || m == Self::SH.country_code() => Self::SH,
            m if m == Self::KN.as_str() || m == Self::KN.country_code() => Self::KN,
            m if m == Self::LC.as_str() || m == Self::LC.country_code() => Self::LC,
            m if m == Self::MF.as_str() || m == Self::MF.country_code() => Self::MF,
            m if m == Self::PM.as_str() || m == Self::PM.country_code() => Self::PM,
            m if m == Self::VC.as_str() || m == Self::VC.country_code() => Self::VC,
            m if m == Self::WS.as_str() || m == Self::WS.country_code() => Self::WS,
            m if m == Self::SM.as_str() || m == Self::SM.country_code() => Self::SM,
            m if m == Self::ST.as_str() || m == Self::ST.country_code() => Self::ST,
            m if m == Self::SA.as_str() || m == Self::SA.country_code() => Self::SA,
            m if m == Self::SN.as_str() || m == Self::SN.country_code() => Self::SN,
            m if m == Self::RS.as_str() || m == Self::RS.country_code() => Self::RS,
            m if m == Self::SC.as_str() || m == Self::SC.country_code() => Self::SC,
            m if m == Self::SL.as_str() || m == Self::SL.country_code() => Self::SL,
            m if m == Self::SG.as_str() || m == Self::SG.country_code() => Self::SG,
            m if m == Self::SX.as_str() || m == Self::SX.country_code() => Self::SX,
            m if m == Self::SK.as_str() || m == Self::SK.country_code() => Self::SK,
            m if m == Self::SI.as_str() || m == Self::SI.country_code() => Self::SI,
            m if m == Self::SB.as_str() || m == Self::SB.country_code() => Self::SB,
            m if m == Self::SO.as_str() || m == Self::SO.country_code() => Self::SO,
            m if m == Self::ZA.as_str() || m == Self::ZA.country_code() => Self::ZA,
            m if m == Self::GS.as_str() || m == Self::GS.country_code() => Self::GS,
            m if m == Self::SS.as_str() || m == Self::SS.country_code() => Self::SS,
            m if m == Self::ES.as_str() || m == Self::ES.country_code() => Self::ES,
            m if m == Self::LK.as_str() || m == Self::LK.country_code() => Self::LK,
            m if m == Self::SD.as_str() || m == Self::SD.country_code() => Self::SD,
            m if m == Self::SR.as_str() || m == Self::SR.country_code() => Self::SR,
            m if m == Self::SJ.as_str() || m == Self::SJ.country_code() => Self::SJ,
            m if m == Self::SZ.as_str() || m == Self::SZ.country_code() => Self::SZ,
            m if m == Self::SE.as_str() || m == Self::SE.country_code() => Self::SE,
            m if m == Self::CH.as_str() || m == Self::CH.country_code() => Self::CH,
            m if m == Self::SY.as_str() || m == Self::SY.country_code() => Self::SY,
            m if m == Self::TW.as_str() || m == Self::TW.country_code() => Self::TW,
            m if m == Self::TJ.as_str() || m == Self::TJ.country_code() => Self::TJ,
            m if m == Self::TZ.as_str() || m == Self::TZ.country_code() => Self::TZ,
            m if m == Self::TH.as_str() || m == Self::TH.country_code() => Self::TH,
            m if m == Self::TL.as_str() || m == Self::TL.country_code() => Self::TL,
            m if m == Self::TG.as_str() || m == Self::TG.country_code() => Self::TG,
            m if m == Self::TK.as_str() || m == Self::TK.country_code() => Self::TK,
            m if m == Self::TO.as_str() || m == Self::TO.country_code() => Self::TO,
            m if m == Self::TT.as_str() || m == Self::TT.country_code() => Self::TT,
            m if m == Self::TN.as_str() || m == Self::TN.country_code() => Self::TN,
            m if m == Self::TR.as_str() || m == Self::TR.country_code() => Self::TR,
            m if m == Self::TM.as_str() || m == Self::TM.country_code() => Self::TM,
            m if m == Self::TC.as_str() || m == Self::TC.country_code() => Self::TC,
            m if m == Self::TV.as_str() || m == Self::TV.country_code() => Self::TV,
            m if m == Self::UG.as_str() || m == Self::UG.country_code() => Self::UG,
            m if m == Self::UA.as_str() || m == Self::UA.country_code() => Self::UA,
            m if m == Self::AE.as_str() || m == Self::AE.country_code() => Self::AE,
            m if m == Self::GB.as_str() || m == Self::GB.country_code() => Self::GB,
            m if m == Self::US.as_str() || m == Self::US.country_code() => Self::US,
            m if m == Self::UM.as_str() || m == Self::UM.country_code() => Self::UM,
            m if m == Self::UY.as_str() || m == Self::UY.country_code() => Self::UY,
            m if m == Self::UZ.as_str() || m == Self::UZ.country_code() => Self::UZ,
            m if m == Self::VU.as_str() || m == Self::VU.country_code() => Self::VU,
            m if m == Self::VE.as_str() || m == Self::VE.country_code() => Self::VE,
            m if m == Self::VN.as_str() || m == Self::VN.country_code() => Self::VN,
            m if m == Self::VG.as_str() || m == Self::VG.country_code() => Self::VG,
            m if m == Self::VI.as_str() || m == Self::VI.country_code() => Self::VI,
            m if m == Self::WF.as_str() || m == Self::WF.country_code() => Self::WF,
            m if m == Self::EH.as_str() || m == Self::EH.country_code() => Self::EH,
            m if m == Self::YE.as_str() || m == Self::YE.country_code() => Self::YE,
            m if m == Self::ZM.as_str() || m == Self::ZM.country_code() => Self::ZM,
            m if m == Self::ZW.as_str() || m == Self::ZW.country_code() => Self::ZW,
            _ => Self::UnsupportedIso31661,
        }
    }
}
