name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Build with `std` and `small_keys` enabled
      run: cargo build --verbose --features std,small_keys
    - name: Build with `std` and `large_keys` enabled
      run: cargo build --verbose --features std,large_keys
    - name: Build  with `std` disabled
      run: cargo build --verbose
    - name: Run tests with `std` and `small_keys` enabled
      run: cargo test --verbose  --features std,small_keys  -- --no-capture
    - name: Run tests with `std` and `large_keys` enabled
      run: cargo test --verbose  --features std,large_keys  -- --no-capture
    - name: Run tests with `std` disabled
      run: cargo test --lib --tests --verbose 
