name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Build with `std` enabled
      run: cargo build --verbose --features std
    - name: Build  with `std` disabled
      run: cargo build --verbose
    - name: Run tests with `std` enabled
      run: cargo test --verbose  --features std  -- --no-capture
    - name: Run tests with `std` disabled
      run: cargo test --lib --tests --verbose 
